<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('group');
$_e_[2] = $_b_->build('group');
$_e_[3] = $_b_->build('img');
$_e_[3]->set('eid', 'obrazek_sipka');
$_e_[3]->set('src', '/image/sipka.gif');
$_e_[3]->set('alt', 'šipka');
$_e_[3]->set('title', '');
$_e_[3]->set('width', '8');
$_e_[3]->set('height', '5');
$_e_[4] = $_b_->build('img');
$_e_[4]->set('eid', 'obrazek_produktu');
$_e_[4]->set('alt', '');
$_e_[4]->set('title', '');
$_e_[4]->set('width', '150');
$_e_[4]->set('height', '200');
$_e_[5] = $_b_->build('img');
$_e_[5]->set('eid', 'obrazek_vlastnost_ikona');
$_e_[5]->set('width', '16');
$_e_[5]->set('height', '16');
$_e_[6] = $_b_->build('img');
$_e_[6]->set('eid', 'obrazek_vlastnost_barva');
$_e_[6]->set('width', '16');
$_e_[6]->set('height', '16');
$_e_[7] = $_b_->build('group');
$_e_[7]->set('eid', 'vyberova_vlastnost_prirustek_height_popup');
$_e_[7]->set('specification', '30px');
$_e_[8] = $_b_->build('navpoint');
$_e_[9] = $_b_->build('span');
$_e_[10] = $_b_->build('text_content');
$_e_[10]->set('text', 'vložit do košíku');
$_e_[9]->add($_e_[10]);
$_e_[8]->set('eid', 'link_objednat');
$_e_[8]->set('page', 'objednávka');
$_e_[8]->set('popup', 'height=400px,width=700px,top=100px,left=100px,menubar=no,toolbar=no,resizable=no,scrollbars=no');
$_e_[8]->set('title', 'objednat');
$_e_[8]->set('class', 'objednat');
$_e_[8]->add($_e_[9]);
$_e_[11] = $_b_->build('tr');
$_e_[12] = $_b_->build('td');
$_e_[13] = $_b_->build('text');
$_e_[13]->set('eid', 'nazev_vlastnosti');
$_e_[14] = $_b_->build('text_content');
$_e_[14]->set('text', ':');
$_e_[12]->set('class', 'atribut');
$_e_[12]->set('rowspan', '1');
$_e_[12]->set('colspan', '1');
$_e_[12]->add($_e_[13]);
$_e_[12]->add($_e_[14]);
$_e_[15] = $_b_->build('td');
$_e_[16] = $_b_->build('inline');
$_e_[16]->set('eid', 'hodnoty_vlastnosti');
$_e_[15]->set('class', 'hodnota');
$_e_[15]->set('rowspan', '1');
$_e_[15]->set('colspan', '1');
$_e_[15]->add($_e_[16]);
$_e_[11]->set('eid', 'ma_vlastnost_vzor');
$_e_[11]->add($_e_[12]);
$_e_[11]->add($_e_[15]);
$_e_[17] = $_b_->build('tr');
$_e_[18] = $_b_->build('td');
$_e_[19] = $_b_->build('text');
$_e_[19]->set('eid', 'nazev_vlastnosti');
$_e_[20] = $_b_->build('text_content');
$_e_[20]->set('text', ':');
$_e_[18]->set('class', 'atribut');
$_e_[18]->set('rowspan', '1');
$_e_[18]->set('colspan', '1');
$_e_[18]->add($_e_[19]);
$_e_[18]->add($_e_[20]);
$_e_[21] = $_b_->build('td');
$_e_[22] = $_b_->build('he');
$_e_[22]->set('code', 'ndash');
$_e_[21]->set('class', 'hodnota');
$_e_[21]->set('rowspan', '1');
$_e_[21]->set('colspan', '1');
$_e_[21]->add($_e_[22]);
$_e_[17]->set('eid', 'nema_vlastnost_vzor');
$_e_[17]->add($_e_[18]);
$_e_[17]->add($_e_[21]);
$_e_[23] = $_b_->build('div');
$_e_[24] = $_b_->build('flow');
$_e_[24]->set('eid', 'umisteni_obsah');
$_e_[23]->set('eid', 'umisteni_vzor');
$_e_[23]->set('class', 'lista');
$_e_[23]->add($_e_[24]);
$_e_[2]->set('eid', 'zaklad_vzory');
$_e_[2]->add($_e_[3]);
$_e_[2]->add($_e_[4]);
$_e_[2]->add($_e_[5]);
$_e_[2]->add($_e_[6]);
$_e_[2]->add($_e_[7]);
$_e_[2]->add($_e_[8]);
$_e_[2]->add($_e_[11]);
$_e_[2]->add($_e_[17]);
$_e_[2]->add($_e_[23]);
$_e_[25] = $_b_->build('rows');
$_e_[26] = $_b_->build('tr');
$_e_[27] = $_b_->build('columns');
$_e_[27]->set('eid', 'produkt');
$_e_[27]->set('specification', '1');
$_e_[26]->add($_e_[27]);
$_e_[28] = $_b_->build('tr');
$_e_[29] = $_b_->build('columns');
$_e_[29]->set('eid', 'produkt');
$_e_[29]->set('specification', '2');
$_e_[28]->add($_e_[29]);
$_e_[25]->set('eid', 'radek_struktura');
$_e_[25]->add($_e_[26]);
$_e_[25]->add($_e_[28]);
$_e_[30] = $_b_->build('group');
$_e_[31] = $_b_->build('columns');
$_e_[32] = $_b_->build('td');
$_e_[33] = $_b_->build('h2');
$_e_[34] = $_b_->build('a');
$_e_[35] = $_b_->build('text');
$_e_[35]->set('eid', 'nazev');
$_e_[34]->set('eid', 'detail');
$_e_[34]->set('title', '');
$_e_[34]->set('shape', 'rect');
$_e_[34]->add($_e_[35]);
$_e_[33]->add($_e_[34]);
$_e_[36] = $_b_->build('div');
$_e_[37] = $_b_->build('span');
$_e_[38] = $_b_->build('text_content');
$_e_[38]->set('text', 'Novinka');
$_e_[37]->set('eid', 'neni_novinka');
$_e_[37]->add($_e_[38]);
$_e_[39] = $_b_->build('text');
$_e_[40] = $_b_->build('text_content');
$_e_[40]->set('text', 'Novinka');
$_e_[39]->set('eid', 'je_novinka');
$_e_[39]->add($_e_[40]);
$_e_[41] = $_b_->build('text_content');
$_e_[41]->set('text', ' | ');
$_e_[42] = $_b_->build('span');
$_e_[43] = $_b_->build('text_content');
$_e_[43]->set('text', 'Akce');
$_e_[42]->set('eid', 'je_akce');
$_e_[42]->add($_e_[43]);
$_e_[44] = $_b_->build('text');
$_e_[45] = $_b_->build('text_content');
$_e_[45]->set('text', 'Akce');
$_e_[44]->set('eid', 'neni_akce');
$_e_[44]->add($_e_[45]);
$_e_[46] = $_b_->build('text_content');
$_e_[46]->set('text', ' | ');
$_e_[47] = $_b_->build('span');
$_e_[48] = $_b_->build('text_content');
$_e_[48]->set('text', 'Sleva');
$_e_[47]->set('eid', 'je_sleva');
$_e_[47]->add($_e_[48]);
$_e_[49] = $_b_->build('text');
$_e_[50] = $_b_->build('text_content');
$_e_[50]->set('text', 'Sleva');
$_e_[49]->set('eid', 'neni_sleva');
$_e_[49]->add($_e_[50]);
$_e_[36]->set('class', 'akce');
$_e_[36]->add($_e_[37]);
$_e_[36]->add($_e_[39]);
$_e_[36]->add($_e_[41]);
$_e_[36]->add($_e_[42]);
$_e_[36]->add($_e_[44]);
$_e_[36]->add($_e_[46]);
$_e_[36]->add($_e_[47]);
$_e_[36]->add($_e_[49]);
$_e_[51] = $_b_->build('flow');
$_e_[52] = $_b_->build('a');
$_e_[53] = $_b_->build('inline');
$_e_[53]->set('eid', 'fotografie');
$_e_[52]->set('eid', 'detail');
$_e_[52]->set('title', '');
$_e_[52]->set('shape', 'rect');
$_e_[52]->add($_e_[53]);
$_e_[51]->set('eid', 'ma_fotografii');
$_e_[51]->add($_e_[52]);
$_e_[54] = $_b_->build('img');
$_e_[54]->set('eid', 'nema_fotografii');
$_e_[54]->set('src', '/image/na-catalog.gif');
$_e_[54]->set('alt', 'obrázek není k dispozici');
$_e_[54]->set('title', '');
$_e_[54]->set('width', '150');
$_e_[54]->set('height', '200');
$_e_[55] = $_b_->build('flow');
$_e_[56] = $_b_->build('p');
$_e_[57] = $_b_->build('inline');
$_e_[57]->set('eid', 'vlastnost');
$_e_[57]->set('specification', '3');
$_e_[56]->add($_e_[57]);
$_e_[55]->set('eid', 'ma_vlastnost');
$_e_[55]->set('specification', '3');
$_e_[55]->add($_e_[56]);
$_e_[58] = $_b_->build('flow');
$_e_[59] = $_b_->build('p');
$_e_[59]->set('eid', 'kratky_popis');
$_e_[58]->set('eid', 'ma_kratky_popis');
$_e_[58]->add($_e_[59]);
$_e_[60] = $_b_->build('p');
$_e_[61] = $_b_->build('text_content');
$_e_[61]->set('text', 'Tento produkt nemá žádný popis.');
$_e_[60]->set('eid', 'nema_kratky_popis');
$_e_[60]->add($_e_[61]);
$_e_[32]->set('class', 'td-kat-01');
$_e_[32]->set('rowspan', '1');
$_e_[32]->set('colspan', '1');
$_e_[32]->add($_e_[33]);
$_e_[32]->add($_e_[36]);
$_e_[32]->add($_e_[51]);
$_e_[32]->add($_e_[54]);
$_e_[32]->add($_e_[55]);
$_e_[32]->add($_e_[58]);
$_e_[32]->add($_e_[60]);
$_e_[31]->set('eid', 'produkt_vzor');
$_e_[31]->set('specification', '1');
$_e_[31]->add($_e_[32]);
$_e_[62] = $_b_->build('columns');
$_e_[63] = $_b_->build('td');
$_e_[64] = $_b_->build('div');
$_e_[65] = $_b_->build('span');
$_e_[65]->set('eid', 'stara_cena_s_dph');
$_e_[65]->set('class', 'old');
$_e_[66] = $_b_->build('span');
$_e_[66]->set('eid', 'nova_cena_s_dph');
$_e_[66]->set('class', 'new');
$_e_[64]->set('class', 'cena');
$_e_[64]->add($_e_[65]);
$_e_[64]->add($_e_[66]);
$_e_[67] = $_b_->build('flow');
$_e_[67]->set('eid', 'objednani');
$_e_[63]->set('class', 'td-kat-02');
$_e_[63]->set('rowspan', '1');
$_e_[63]->set('colspan', '1');
$_e_[63]->add($_e_[64]);
$_e_[63]->add($_e_[67]);
$_e_[62]->set('eid', 'produkt_vzor');
$_e_[62]->set('specification', '2');
$_e_[62]->add($_e_[63]);
$_e_[68] = $_b_->build('columns');
$_e_[69] = $_b_->build('td');
$_e_[70] = $_b_->build('h2');
$_e_[71] = $_b_->build('a');
$_e_[72] = $_b_->build('text');
$_e_[72]->set('eid', 'nazev');
$_e_[71]->set('eid', 'detail');
$_e_[71]->set('title', '');
$_e_[71]->set('shape', 'rect');
$_e_[71]->add($_e_[72]);
$_e_[70]->add($_e_[71]);
$_e_[73] = $_b_->build('div');
$_e_[74] = $_b_->build('span');
$_e_[75] = $_b_->build('text_content');
$_e_[75]->set('text', 'Novinka');
$_e_[74]->set('eid', 'neni_novinka');
$_e_[74]->add($_e_[75]);
$_e_[76] = $_b_->build('text');
$_e_[77] = $_b_->build('text_content');
$_e_[77]->set('text', 'Novinka');
$_e_[76]->set('eid', 'je_novinka');
$_e_[76]->add($_e_[77]);
$_e_[78] = $_b_->build('text_content');
$_e_[78]->set('text', ' | ');
$_e_[79] = $_b_->build('span');
$_e_[80] = $_b_->build('text_content');
$_e_[80]->set('text', 'Akce');
$_e_[79]->set('eid', 'je_akce');
$_e_[79]->add($_e_[80]);
$_e_[81] = $_b_->build('text');
$_e_[82] = $_b_->build('text_content');
$_e_[82]->set('text', 'Akce');
$_e_[81]->set('eid', 'neni_akce');
$_e_[81]->add($_e_[82]);
$_e_[83] = $_b_->build('text_content');
$_e_[83]->set('text', ' | ');
$_e_[84] = $_b_->build('span');
$_e_[85] = $_b_->build('text_content');
$_e_[85]->set('text', 'Sleva');
$_e_[84]->set('eid', 'je_sleva');
$_e_[84]->add($_e_[85]);
$_e_[86] = $_b_->build('text');
$_e_[87] = $_b_->build('text_content');
$_e_[87]->set('text', 'Sleva');
$_e_[86]->set('eid', 'neni_sleva');
$_e_[86]->add($_e_[87]);
$_e_[73]->set('class', 'akce');
$_e_[73]->add($_e_[74]);
$_e_[73]->add($_e_[76]);
$_e_[73]->add($_e_[78]);
$_e_[73]->add($_e_[79]);
$_e_[73]->add($_e_[81]);
$_e_[73]->add($_e_[83]);
$_e_[73]->add($_e_[84]);
$_e_[73]->add($_e_[86]);
$_e_[88] = $_b_->build('a');
$_e_[89] = $_b_->build('inline');
$_e_[89]->set('eid', 'fotografie');
$_e_[88]->set('eid', 'detail');
$_e_[88]->set('title', '');
$_e_[88]->set('shape', 'rect');
$_e_[88]->add($_e_[89]);
$_e_[90] = $_b_->build('flow');
$_e_[91] = $_b_->build('p');
$_e_[92] = $_b_->build('inline');
$_e_[92]->set('eid', 'vlastnost');
$_e_[92]->set('specification', '3');
$_e_[91]->add($_e_[92]);
$_e_[90]->set('eid', 'ma_vlastnost');
$_e_[90]->set('specification', '3');
$_e_[90]->add($_e_[91]);
$_e_[93] = $_b_->build('flow');
$_e_[94] = $_b_->build('p');
$_e_[94]->set('eid', 'popis');
$_e_[93]->set('eid', 'ma_popis');
$_e_[93]->add($_e_[94]);
$_e_[95] = $_b_->build('p');
$_e_[96] = $_b_->build('text_content');
$_e_[96]->set('text', 'Tento produkt nemá žádný popis.');
$_e_[95]->set('eid', 'nema_popis');
$_e_[95]->add($_e_[96]);
$_e_[69]->set('class', 'td-kat-01');
$_e_[69]->set('rowspan', '1');
$_e_[69]->set('colspan', '1');
$_e_[69]->add($_e_[70]);
$_e_[69]->add($_e_[73]);
$_e_[69]->add($_e_[88]);
$_e_[69]->add($_e_[90]);
$_e_[69]->add($_e_[93]);
$_e_[69]->add($_e_[95]);
$_e_[68]->set('eid', 'levy_produkt_vzor');
$_e_[68]->set('specification', '1');
$_e_[68]->add($_e_[69]);
$_e_[97] = $_b_->build('columns');
$_e_[98] = $_b_->build('td');
$_e_[99] = $_b_->build('div');
$_e_[100] = $_b_->build('span');
$_e_[100]->set('eid', 'stara_cena_s_dph');
$_e_[100]->set('class', 'old');
$_e_[101] = $_b_->build('span');
$_e_[101]->set('eid', 'nova_cena_s_dph');
$_e_[101]->set('class', 'new');
$_e_[99]->set('class', 'cena');
$_e_[99]->add($_e_[100]);
$_e_[99]->add($_e_[101]);
$_e_[102] = $_b_->build('flow');
$_e_[102]->set('eid', 'objednani');
$_e_[98]->set('class', 'td-kat-02');
$_e_[98]->set('rowspan', '1');
$_e_[98]->set('colspan', '1');
$_e_[98]->add($_e_[99]);
$_e_[98]->add($_e_[102]);
$_e_[97]->set('eid', 'levy_produkt_vzor');
$_e_[97]->set('specification', '2');
$_e_[97]->add($_e_[98]);
$_e_[103] = $_b_->build('columns');
$_e_[104] = $_b_->build('td');
$_e_[105] = $_b_->build('h2');
$_e_[106] = $_b_->build('a');
$_e_[107] = $_b_->build('text');
$_e_[107]->set('eid', 'nazev');
$_e_[106]->set('eid', 'detail');
$_e_[106]->set('title', '');
$_e_[106]->set('shape', 'rect');
$_e_[106]->add($_e_[107]);
$_e_[105]->add($_e_[106]);
$_e_[108] = $_b_->build('div');
$_e_[109] = $_b_->build('span');
$_e_[110] = $_b_->build('text_content');
$_e_[110]->set('text', 'Novinka');
$_e_[109]->set('eid', 'neni_novinka');
$_e_[109]->add($_e_[110]);
$_e_[111] = $_b_->build('text');
$_e_[112] = $_b_->build('text_content');
$_e_[112]->set('text', 'Novinka');
$_e_[111]->set('eid', 'je_novinka');
$_e_[111]->add($_e_[112]);
$_e_[113] = $_b_->build('text_content');
$_e_[113]->set('text', ' | ');
$_e_[114] = $_b_->build('span');
$_e_[115] = $_b_->build('text_content');
$_e_[115]->set('text', 'Akce');
$_e_[114]->set('eid', 'je_akce');
$_e_[114]->add($_e_[115]);
$_e_[116] = $_b_->build('text');
$_e_[117] = $_b_->build('text_content');
$_e_[117]->set('text', 'Akce');
$_e_[116]->set('eid', 'neni_akce');
$_e_[116]->add($_e_[117]);
$_e_[118] = $_b_->build('text_content');
$_e_[118]->set('text', ' | ');
$_e_[119] = $_b_->build('span');
$_e_[120] = $_b_->build('text_content');
$_e_[120]->set('text', 'Sleva');
$_e_[119]->set('eid', 'je_sleva');
$_e_[119]->add($_e_[120]);
$_e_[121] = $_b_->build('text');
$_e_[122] = $_b_->build('text_content');
$_e_[122]->set('text', 'Sleva');
$_e_[121]->set('eid', 'neni_sleva');
$_e_[121]->add($_e_[122]);
$_e_[108]->set('class', 'akce');
$_e_[108]->add($_e_[109]);
$_e_[108]->add($_e_[111]);
$_e_[108]->add($_e_[113]);
$_e_[108]->add($_e_[114]);
$_e_[108]->add($_e_[116]);
$_e_[108]->add($_e_[118]);
$_e_[108]->add($_e_[119]);
$_e_[108]->add($_e_[121]);
$_e_[123] = $_b_->build('a');
$_e_[124] = $_b_->build('inline');
$_e_[124]->set('eid', 'fotografie');
$_e_[123]->set('eid', 'detail');
$_e_[123]->set('title', '');
$_e_[123]->set('shape', 'rect');
$_e_[123]->add($_e_[124]);
$_e_[125] = $_b_->build('flow');
$_e_[126] = $_b_->build('p');
$_e_[127] = $_b_->build('inline');
$_e_[127]->set('eid', 'vlastnost');
$_e_[127]->set('specification', '3');
$_e_[126]->add($_e_[127]);
$_e_[125]->set('eid', 'ma_vlastnost');
$_e_[125]->set('specification', '3');
$_e_[125]->add($_e_[126]);
$_e_[128] = $_b_->build('flow');
$_e_[129] = $_b_->build('p');
$_e_[129]->set('eid', 'popis');
$_e_[128]->set('eid', 'ma_popis');
$_e_[128]->add($_e_[129]);
$_e_[130] = $_b_->build('p');
$_e_[131] = $_b_->build('text_content');
$_e_[131]->set('text', 'Tento produkt nemá žádný popis.');
$_e_[130]->set('eid', 'nema_popis');
$_e_[130]->add($_e_[131]);
$_e_[104]->set('class', 'td-kat-01');
$_e_[104]->set('rowspan', '1');
$_e_[104]->set('colspan', '1');
$_e_[104]->add($_e_[105]);
$_e_[104]->add($_e_[108]);
$_e_[104]->add($_e_[123]);
$_e_[104]->add($_e_[125]);
$_e_[104]->add($_e_[128]);
$_e_[104]->add($_e_[130]);
$_e_[103]->set('eid', 'pravy_produkt_vzor');
$_e_[103]->set('specification', '1');
$_e_[103]->add($_e_[104]);
$_e_[132] = $_b_->build('columns');
$_e_[133] = $_b_->build('td');
$_e_[134] = $_b_->build('div');
$_e_[135] = $_b_->build('span');
$_e_[135]->set('eid', 'stara_cena_s_dph');
$_e_[135]->set('class', 'old');
$_e_[136] = $_b_->build('span');
$_e_[136]->set('eid', 'nova_cena_s_dph');
$_e_[136]->set('class', 'new');
$_e_[134]->set('class', 'cena');
$_e_[134]->add($_e_[135]);
$_e_[134]->add($_e_[136]);
$_e_[137] = $_b_->build('flow');
$_e_[137]->set('eid', 'objednani');
$_e_[133]->set('class', 'td-kat-02');
$_e_[133]->set('rowspan', '1');
$_e_[133]->set('colspan', '1');
$_e_[133]->add($_e_[134]);
$_e_[133]->add($_e_[137]);
$_e_[132]->set('eid', 'pravy_produkt_vzor');
$_e_[132]->set('specification', '2');
$_e_[132]->add($_e_[133]);
$_e_[138] = $_b_->build('columns');
$_e_[139] = $_b_->build('td');
$_e_[140] = $_b_->build('he');
$_e_[140]->set('code', 'nbsp');
$_e_[139]->set('class', 'white');
$_e_[139]->set('rowspan', '1');
$_e_[139]->set('colspan', '1');
$_e_[139]->add($_e_[140]);
$_e_[138]->set('eid', 'neni_produkt_vzor');
$_e_[138]->set('specification', '1');
$_e_[138]->add($_e_[139]);
$_e_[141] = $_b_->build('columns');
$_e_[142] = $_b_->build('td');
$_e_[143] = $_b_->build('he');
$_e_[143]->set('code', 'nbsp');
$_e_[142]->set('class', 'white');
$_e_[142]->set('rowspan', '1');
$_e_[142]->set('colspan', '1');
$_e_[142]->add($_e_[143]);
$_e_[141]->set('eid', 'neni_produkt_vzor');
$_e_[141]->set('specification', '2');
$_e_[141]->add($_e_[142]);
$_e_[144] = $_b_->build('columns');
$_e_[145] = $_b_->build('td');
$_e_[146] = $_b_->build('he');
$_e_[146]->set('code', 'nbsp');
$_e_[145]->set('class', 'white');
$_e_[145]->set('rowspan', '1');
$_e_[145]->set('colspan', '1');
$_e_[145]->add($_e_[146]);
$_e_[144]->set('eid', 'levy_neni_produkt_vzor');
$_e_[144]->set('specification', '1');
$_e_[144]->add($_e_[145]);
$_e_[147] = $_b_->build('columns');
$_e_[148] = $_b_->build('td');
$_e_[149] = $_b_->build('he');
$_e_[149]->set('code', 'nbsp');
$_e_[148]->set('class', 'white');
$_e_[148]->set('rowspan', '1');
$_e_[148]->set('colspan', '1');
$_e_[148]->add($_e_[149]);
$_e_[147]->set('eid', 'levy_neni_produkt_vzor');
$_e_[147]->set('specification', '2');
$_e_[147]->add($_e_[148]);
$_e_[150] = $_b_->build('columns');
$_e_[151] = $_b_->build('td');
$_e_[152] = $_b_->build('he');
$_e_[152]->set('code', 'nbsp');
$_e_[151]->set('class', 'white');
$_e_[151]->set('rowspan', '1');
$_e_[151]->set('colspan', '1');
$_e_[151]->add($_e_[152]);
$_e_[150]->set('eid', 'pravy_neni_produkt_vzor');
$_e_[150]->set('specification', '1');
$_e_[150]->add($_e_[151]);
$_e_[153] = $_b_->build('columns');
$_e_[154] = $_b_->build('td');
$_e_[155] = $_b_->build('he');
$_e_[155]->set('code', 'nbsp');
$_e_[154]->set('class', 'white');
$_e_[154]->set('rowspan', '1');
$_e_[154]->set('colspan', '1');
$_e_[154]->add($_e_[155]);
$_e_[153]->set('eid', 'pravy_neni_produkt_vzor');
$_e_[153]->set('specification', '2');
$_e_[153]->add($_e_[154]);
$_e_[30]->set('eid', 'produkt_vzory');
$_e_[30]->add($_e_[31]);
$_e_[30]->add($_e_[62]);
$_e_[30]->add($_e_[68]);
$_e_[30]->add($_e_[97]);
$_e_[30]->add($_e_[103]);
$_e_[30]->add($_e_[132]);
$_e_[30]->add($_e_[138]);
$_e_[30]->add($_e_[141]);
$_e_[30]->add($_e_[144]);
$_e_[30]->add($_e_[147]);
$_e_[30]->add($_e_[150]);
$_e_[30]->add($_e_[153]);
$_e_[1]->set('active', '0');
$_e_[1]->add($_e_[2]);
$_e_[1]->add($_e_[25]);
$_e_[1]->add($_e_[30]);
$_e_[156] = $_b_->build('p');
$_e_[157] = $_b_->build('text_content');
$_e_[157]->set('text', 'Nenalezeny žádné produkty.');
$_e_[156]->set('eid', 'nejsou_produkty');
$_e_[156]->add($_e_[157]);
$_e_[158] = $_b_->build('p');
$_e_[159] = $_b_->build('text_content');
$_e_[159]->set('text', 'Nenalezeny žádné produkty, číslo stránky je příliš vysoké.');
$_e_[158]->set('eid', 'prazdna_stranka');
$_e_[158]->add($_e_[159]);
$_e_[160] = $_b_->build('pagination');
$_e_[160]->set('eid', 'horni_paginace');
$_e_[160]->set('vid', 'paginace');
$_e_[160]->set('case', 'top');
$_e_[160]->set('radius', '2');
$_e_[161] = $_b_->build('flow');
$_e_[162] = $_b_->build('table');
$_e_[162]->set('eid', 'produkty');
$_e_[162]->set('id', 'tab-katalog');
$_e_[162]->set('cellspacing', '0');
$_e_[162]->set('cellpadding', '0');
$_e_[161]->set('eid', 'jsou_produkty');
$_e_[161]->add($_e_[162]);
$_e_[163] = $_b_->build('pagination');
$_e_[163]->set('eid', 'dolni_paginace');
$_e_[163]->set('vid', 'paginace');
$_e_[163]->set('case', 'bottom');
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[156]);
$_e_[0]->add($_e_[158]);
$_e_[0]->add($_e_[160]);
$_e_[0]->add($_e_[161]);
$_e_[0]->add($_e_[163]);
?>