<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('require');
$_e_[2] = $_b_->build('link');
$_e_[2]->set('rel', 'stylesheet');
$_e_[2]->set('type', 'text/css');
$_e_[2]->set('href', '/styles/katalog.css');
$_e_[1]->add($_e_[2]);
$_e_[3] = $_b_->build('group');
$_e_[4] = $_b_->build('img');
$_e_[4]->set('eid', 'obrazek_sipka');
$_e_[4]->set('src', '/image/sipka.png');
$_e_[4]->set('alt', 'šipka');
$_e_[4]->set('title', '');
$_e_[4]->set('width', '24');
$_e_[4]->set('height', '24');
$_e_[5] = $_b_->build('img');
$_e_[5]->set('eid', 'obrazek_hlavni');
$_e_[5]->set('alt', '');
$_e_[5]->set('title', '');
$_e_[5]->set('width', '320');
$_e_[5]->set('height', '400');
$_e_[6] = $_b_->build('img');
$_e_[6]->set('eid', 'obrazek_dalsi');
$_e_[6]->set('alt', '');
$_e_[6]->set('title', '');
$_e_[6]->set('width', '90');
$_e_[6]->set('height', '67');
$_e_[7] = $_b_->build('img');
$_e_[7]->set('eid', 'obrazek_ilustrativni');
$_e_[7]->set('alt', '');
$_e_[7]->set('title', '');
$_e_[7]->set('width', '90');
$_e_[7]->set('height', '67');
$_e_[8] = $_b_->build('img');
$_e_[8]->set('eid', 'obrazek_kolekce');
$_e_[8]->set('alt', '');
$_e_[8]->set('title', '');
$_e_[8]->set('width', '90');
$_e_[8]->set('height', '67');
$_e_[9] = $_b_->build('flow');
$_e_[10] = $_b_->build('inline');
$_e_[10]->set('eid', 'priloha_pripona');
$_e_[10]->set('specification', 'pdf');
$_e_[11] = $_b_->build('a');
$_e_[12] = $_b_->build('img');
$_e_[12]->set('src', '/image/ico-pdf.gif');
$_e_[12]->set('alt', 'soubor s PDF');
$_e_[12]->set('width', '20');
$_e_[12]->set('height', '20');
$_e_[13] = $_b_->build('span');
$_e_[14] = $_b_->build('inline');
$_e_[14]->set('eid', 'priloha_nazev');
$_e_[13]->add($_e_[14]);
$_e_[11]->set('eid', 'priloha_odkaz');
$_e_[11]->set('target', '_blank');
$_e_[11]->set('shape', 'rect');
$_e_[11]->add($_e_[12]);
$_e_[11]->add($_e_[13]);
$_e_[9]->set('eid', 'priloha_vzor');
$_e_[9]->add($_e_[10]);
$_e_[9]->add($_e_[11]);
$_e_[15] = $_b_->build('img');
$_e_[15]->set('eid', 'obrazek_vlastnost_ikona');
$_e_[15]->set('width', '30');
$_e_[15]->set('height', '30');
$_e_[16] = $_b_->build('img');
$_e_[16]->set('eid', 'obrazek_vlastnost_barva');
$_e_[16]->set('width', '16');
$_e_[16]->set('height', '16');
$_e_[17] = $_b_->build('group');
$_e_[17]->set('eid', 'vyberova_vlastnost_prirustek_height_popup');
$_e_[17]->set('specification', '30px');
$_e_[18] = $_b_->build('navpoint');
$_e_[19] = $_b_->build('img');
$_e_[19]->set('src', '/image/objednat2.gif');
$_e_[19]->set('alt', '');
$_e_[19]->set('title', 'objednat');
$_e_[19]->set('width', '180');
$_e_[19]->set('height', '26');
$_e_[18]->set('eid', 'link_objednat');
$_e_[18]->set('page', 'objednávka');
$_e_[18]->set('popup', 'height=400px,width=700px,top=100px,left=100px,menubar=no,toolbar=no,resizable=no,scrollbars=no');
$_e_[18]->set('title', 'objednat');
$_e_[18]->set('class', 'objednat2');
$_e_[18]->add($_e_[19]);
$_e_[20] = $_b_->build('tr');
$_e_[21] = $_b_->build('td');
$_e_[22] = $_b_->build('text');
$_e_[22]->set('eid', 'nazev_vlastnosti');
$_e_[23] = $_b_->build('text_content');
$_e_[23]->set('text', ':');
$_e_[21]->set('class', 'atribut');
$_e_[21]->set('rowspan', '1');
$_e_[21]->set('colspan', '1');
$_e_[21]->add($_e_[22]);
$_e_[21]->add($_e_[23]);
$_e_[24] = $_b_->build('td');
$_e_[25] = $_b_->build('inline');
$_e_[25]->set('eid', 'hodnoty_vlastnosti');
$_e_[24]->set('class', 'hodnota');
$_e_[24]->set('rowspan', '1');
$_e_[24]->set('colspan', '1');
$_e_[24]->add($_e_[25]);
$_e_[20]->set('eid', 'ma_vlastnost_vzor');
$_e_[20]->add($_e_[21]);
$_e_[20]->add($_e_[24]);
$_e_[26] = $_b_->build('rows');
$_e_[26]->set('eid', 'nema_vlastnost_vzor');
$_e_[27] = $_b_->build('div');
$_e_[28] = $_b_->build('flow');
$_e_[28]->set('eid', 'umisteni_obsah');
$_e_[27]->set('eid', 'umisteni_vzor');
$_e_[27]->set('class', 'navigace');
$_e_[27]->add($_e_[28]);
$_e_[3]->set('active', '0');
$_e_[3]->add($_e_[4]);
$_e_[3]->add($_e_[5]);
$_e_[3]->add($_e_[6]);
$_e_[3]->add($_e_[7]);
$_e_[3]->add($_e_[8]);
$_e_[3]->add($_e_[9]);
$_e_[3]->add($_e_[15]);
$_e_[3]->add($_e_[16]);
$_e_[3]->add($_e_[17]);
$_e_[3]->add($_e_[18]);
$_e_[3]->add($_e_[20]);
$_e_[3]->add($_e_[26]);
$_e_[3]->add($_e_[27]);
$_e_[29] = $_b_->build('table');
$_e_[30] = $_b_->build('tr');
$_e_[31] = $_b_->build('td');
$_e_[32] = $_b_->build('flow');
$_e_[32]->set('eid', 'umisteni');
$_e_[31]->set('colspan', '2');
$_e_[31]->set('rowspan', '1');
$_e_[31]->add($_e_[32]);
$_e_[30]->add($_e_[31]);
$_e_[33] = $_b_->build('tr');
$_e_[34] = $_b_->build('td');
$_e_[35] = $_b_->build('h3');
$_e_[36] = $_b_->build('text');
$_e_[36]->set('eid', 'nazev');
$_e_[35]->add($_e_[36]);
$_e_[34]->set('class', 't-d-nadpis');
$_e_[34]->set('colspan', '2');
$_e_[34]->set('rowspan', '1');
$_e_[34]->add($_e_[35]);
$_e_[33]->add($_e_[34]);
$_e_[37] = $_b_->build('tr');
$_e_[38] = $_b_->build('td');
$_e_[39] = $_b_->build('div');
$_e_[40] = $_b_->build('flow');
$_e_[41] = $_b_->build('a');
$_e_[42] = $_b_->build('inline');
$_e_[42]->set('eid', 'fotografie');
$_e_[41]->set('eid', 'fotografie_odkaz');
$_e_[41]->set('shape', 'rect');
$_e_[41]->add($_e_[42]);
$_e_[40]->set('eid', 'ma_fotografii');
$_e_[40]->add($_e_[41]);
$_e_[43] = $_b_->build('img');
$_e_[43]->set('eid', 'nema_fotografii');
$_e_[43]->set('src', '/image/na-detail.gif');
$_e_[43]->set('alt', 'Bild nicht verfügbar');
$_e_[43]->set('title', 'Bild nicht verfügbar');
$_e_[43]->set('width', '320');
$_e_[43]->set('height', '400');
$_e_[39]->set('class', 't-d-foto-hlavni');
$_e_[39]->add($_e_[40]);
$_e_[39]->add($_e_[43]);
$_e_[44] = $_b_->build('flow');
$_e_[45] = $_b_->build('div');
$_e_[46] = $_b_->build('strong');
$_e_[47] = $_b_->build('text_content');
$_e_[47]->set('text', 'Rarität');
$_e_[46]->add($_e_[47]);
$_e_[45]->set('class', 'raritni');
$_e_[45]->add($_e_[46]);
$_e_[44]->set('eid', 'ma_vlastnost');
$_e_[44]->set('specification', '9');
$_e_[44]->add($_e_[45]);
$_e_[48] = $_b_->build('flow');
$_e_[48]->set('eid', 'nema_vlastnost');
$_e_[48]->set('specification', '9');
$_e_[49] = $_b_->build('div');
$_e_[50] = $_b_->build('flow');
$_e_[51] = $_b_->build('span');
$_e_[52] = $_b_->build('strong');
$_e_[53] = $_b_->build('text_content');
$_e_[53]->set('text', 'Neu');
$_e_[52]->add($_e_[53]);
$_e_[51]->set('class', 'novinka');
$_e_[51]->add($_e_[52]);
$_e_[50]->set('eid', 'je_novinka');
$_e_[50]->add($_e_[51]);
$_e_[54] = $_b_->build('flow');
$_e_[54]->set('eid', 'neni_novinka');
$_e_[55] = $_b_->build('flow');
$_e_[56] = $_b_->build('strong');
$_e_[57] = $_b_->build('strong');
$_e_[58] = $_b_->build('text_content');
$_e_[58]->set('text', 'Aktion');
$_e_[57]->add($_e_[58]);
$_e_[56]->set('class', 'akce');
$_e_[56]->add($_e_[57]);
$_e_[59] = $_b_->build('flow');
$_e_[60] = $_b_->build('div');
$_e_[61] = $_b_->build('span');
$_e_[61]->set('eid', 'zmena_ceny_procent');
$_e_[62] = $_b_->build('strong');
$_e_[63] = $_b_->build('text_content');
$_e_[63]->set('text', '%');
$_e_[62]->add($_e_[63]);
$_e_[60]->set('class', 'procenta-detail');
$_e_[60]->add($_e_[61]);
$_e_[60]->add($_e_[62]);
$_e_[59]->set('eid', 'ma_zmenu_ceny');
$_e_[59]->add($_e_[60]);
$_e_[55]->set('eid', 'je_akce');
$_e_[55]->add($_e_[56]);
$_e_[55]->add($_e_[59]);
$_e_[64] = $_b_->build('flow');
$_e_[64]->set('eid', 'neni_akce');
$_e_[65] = $_b_->build('flow');
$_e_[66] = $_b_->build('strong');
$_e_[67] = $_b_->build('strong');
$_e_[68] = $_b_->build('text_content');
$_e_[68]->set('text', 'Sale');
$_e_[67]->add($_e_[68]);
$_e_[66]->set('class', 'sleva');
$_e_[66]->add($_e_[67]);
$_e_[69] = $_b_->build('flow');
$_e_[70] = $_b_->build('div');
$_e_[71] = $_b_->build('span');
$_e_[71]->set('eid', 'zmena_ceny_procent');
$_e_[72] = $_b_->build('strong');
$_e_[73] = $_b_->build('text_content');
$_e_[73]->set('text', '%');
$_e_[72]->add($_e_[73]);
$_e_[70]->set('class', 'procenta-detail');
$_e_[70]->add($_e_[71]);
$_e_[70]->add($_e_[72]);
$_e_[69]->set('eid', 'ma_zmenu_ceny');
$_e_[69]->add($_e_[70]);
$_e_[65]->set('eid', 'je_sleva');
$_e_[65]->add($_e_[66]);
$_e_[65]->add($_e_[69]);
$_e_[74] = $_b_->build('flow');
$_e_[74]->set('eid', 'neni_sleva');
$_e_[75] = $_b_->build('div');
$_e_[76] = $_b_->build('strong');
$_e_[77] = $_b_->build('text_content');
$_e_[77]->set('text', 'nur');
$_e_[76]->add($_e_[77]);
$_e_[78] = $_b_->build('span');
$_e_[78]->set('eid', 'nova_cena_s_dph');
$_e_[79] = $_b_->build('strong');
$_e_[80] = $_b_->build('text_content');
$_e_[80]->set('text', 'CHF');
$_e_[79]->add($_e_[80]);
$_e_[75]->set('eid', 'nema_zmenu_ceny');
$_e_[75]->set('class', 'new-detail');
$_e_[75]->add($_e_[76]);
$_e_[75]->add($_e_[78]);
$_e_[75]->add($_e_[79]);
$_e_[81] = $_b_->build('flow');
$_e_[82] = $_b_->build('div');
$_e_[83] = $_b_->build('span');
$_e_[83]->set('eid', 'stara_cena_s_dph');
$_e_[84] = $_b_->build('strong');
$_e_[85] = $_b_->build('text_content');
$_e_[85]->set('text', 'CHF');
$_e_[84]->add($_e_[85]);
$_e_[82]->set('class', 'old-detail');
$_e_[82]->add($_e_[83]);
$_e_[82]->add($_e_[84]);
$_e_[86] = $_b_->build('div');
$_e_[87] = $_b_->build('strong');
$_e_[88] = $_b_->build('text_content');
$_e_[88]->set('text', 'nur');
$_e_[87]->add($_e_[88]);
$_e_[89] = $_b_->build('span');
$_e_[89]->set('eid', 'nova_cena_s_dph');
$_e_[90] = $_b_->build('strong');
$_e_[91] = $_b_->build('text_content');
$_e_[91]->set('text', 'CHF');
$_e_[90]->add($_e_[91]);
$_e_[86]->set('class', 'new-detail');
$_e_[86]->add($_e_[87]);
$_e_[86]->add($_e_[89]);
$_e_[86]->add($_e_[90]);
$_e_[81]->set('eid', 'ma_zmenu_ceny');
$_e_[81]->add($_e_[82]);
$_e_[81]->add($_e_[86]);
$_e_[49]->set('class', 'status-produkt');
$_e_[49]->add($_e_[50]);
$_e_[49]->add($_e_[54]);
$_e_[49]->add($_e_[55]);
$_e_[49]->add($_e_[64]);
$_e_[49]->add($_e_[65]);
$_e_[49]->add($_e_[74]);
$_e_[49]->add($_e_[75]);
$_e_[49]->add($_e_[81]);
$_e_[92] = $_b_->build('flow');
$_e_[93] = $_b_->build('div');
$_e_[94] = $_b_->build('flow');
$_e_[94]->set('eid', 'dalsi_fotografie');
$_e_[93]->set('class', 't-d-foto-dalsi');
$_e_[93]->add($_e_[94]);
$_e_[92]->set('eid', 'ma_dalsi_fotografie');
$_e_[92]->add($_e_[93]);
$_e_[95] = $_b_->build('flow');
$_e_[95]->set('eid', 'nema_dalsi_fotografie');
$_e_[96] = $_b_->build('flow');
$_e_[96]->set('active', '0');
$_e_[96]->set('eid', 'objednani');
$_e_[38]->set('class', 't-d-foto');
$_e_[38]->set('rowspan', '2');
$_e_[38]->set('colspan', '1');
$_e_[38]->add($_e_[39]);
$_e_[38]->add($_e_[44]);
$_e_[38]->add($_e_[48]);
$_e_[38]->add($_e_[49]);
$_e_[38]->add($_e_[92]);
$_e_[38]->add($_e_[95]);
$_e_[38]->add($_e_[96]);
$_e_[97] = $_b_->build('td');
$_e_[98] = $_b_->build('div');
$_e_[99] = $_b_->build('table');
$_e_[100] = $_b_->build('rows');
$_e_[100]->set('eid', 'vlastnosti');
$_e_[100]->set('specification', '!9');
$_e_[101] = $_b_->build('tr');
$_e_[102] = $_b_->build('td');
$_e_[103] = $_b_->build('text_content');
$_e_[103]->set('text', 'Cena bez DPH:');
$_e_[102]->set('class', 'atribut');
$_e_[102]->set('rowspan', '1');
$_e_[102]->set('colspan', '1');
$_e_[102]->add($_e_[103]);
$_e_[104] = $_b_->build('td');
$_e_[105] = $_b_->build('inline');
$_e_[106] = $_b_->build('span');
$_e_[106]->set('eid', 'stara_cena_bez_dph');
$_e_[106]->set('class', 'old2');
$_e_[105]->set('eid', 'ma_starou_cenu');
$_e_[105]->add($_e_[106]);
$_e_[107] = $_b_->build('span');
$_e_[108] = $_b_->build('he');
$_e_[108]->set('code', 'mdash');
$_e_[107]->set('eid', 'nema_starou_cenu');
$_e_[107]->set('class', 'old2');
$_e_[107]->add($_e_[108]);
$_e_[109] = $_b_->build('inline');
$_e_[110] = $_b_->build('span');
$_e_[110]->set('eid', 'nova_cena_bez_dph');
$_e_[110]->set('class', 'new2');
$_e_[109]->set('eid', 'ma_novou_cenu');
$_e_[109]->add($_e_[110]);
$_e_[111] = $_b_->build('span');
$_e_[112] = $_b_->build('he');
$_e_[112]->set('code', 'mdash');
$_e_[111]->set('eid', 'nema_novou_cenu');
$_e_[111]->set('class', 'new2');
$_e_[111]->add($_e_[112]);
$_e_[104]->set('class', 'hodnota');
$_e_[104]->set('rowspan', '1');
$_e_[104]->set('colspan', '1');
$_e_[104]->add($_e_[105]);
$_e_[104]->add($_e_[107]);
$_e_[104]->add($_e_[109]);
$_e_[104]->add($_e_[111]);
$_e_[101]->set('active', '0');
$_e_[101]->add($_e_[102]);
$_e_[101]->add($_e_[104]);
$_e_[113] = $_b_->build('tr');
$_e_[114] = $_b_->build('td');
$_e_[115] = $_b_->build('b');
$_e_[116] = $_b_->build('text_content');
$_e_[116]->set('text', 'Cena s DPH:');
$_e_[115]->add($_e_[116]);
$_e_[114]->set('class', 'atribut');
$_e_[114]->set('rowspan', '1');
$_e_[114]->set('colspan', '1');
$_e_[114]->add($_e_[115]);
$_e_[117] = $_b_->build('td');
$_e_[118] = $_b_->build('inline');
$_e_[119] = $_b_->build('span');
$_e_[119]->set('eid', 'stara_cena_s_dph');
$_e_[119]->set('class', 'old3');
$_e_[118]->set('eid', 'ma_starou_cenu');
$_e_[118]->add($_e_[119]);
$_e_[120] = $_b_->build('span');
$_e_[121] = $_b_->build('he');
$_e_[121]->set('code', 'mdash');
$_e_[120]->set('eid', 'nema_starou_cenu');
$_e_[120]->set('class', 'old3');
$_e_[120]->add($_e_[121]);
$_e_[122] = $_b_->build('inline');
$_e_[123] = $_b_->build('span');
$_e_[123]->set('eid', 'nova_cena_s_dph');
$_e_[123]->set('class', 'new3');
$_e_[122]->set('eid', 'ma_novou_cenu');
$_e_[122]->add($_e_[123]);
$_e_[124] = $_b_->build('span');
$_e_[125] = $_b_->build('he');
$_e_[125]->set('code', 'mdash');
$_e_[124]->set('eid', 'nema_novou_cenu');
$_e_[124]->set('class', 'new3');
$_e_[124]->add($_e_[125]);
$_e_[117]->set('class', 'hodnota');
$_e_[117]->set('rowspan', '1');
$_e_[117]->set('colspan', '1');
$_e_[117]->add($_e_[118]);
$_e_[117]->add($_e_[120]);
$_e_[117]->add($_e_[122]);
$_e_[117]->add($_e_[124]);
$_e_[113]->set('active', '0');
$_e_[113]->add($_e_[114]);
$_e_[113]->add($_e_[117]);
$_e_[126] = $_b_->build('tr');
$_e_[127] = $_b_->build('td');
$_e_[128] = $_b_->build('b');
$_e_[129] = $_b_->build('text_content');
$_e_[129]->set('text', 'DPH:');
$_e_[128]->add($_e_[129]);
$_e_[127]->set('class', 'atribut');
$_e_[127]->set('rowspan', '1');
$_e_[127]->set('colspan', '1');
$_e_[127]->add($_e_[128]);
$_e_[130] = $_b_->build('td');
$_e_[131] = $_b_->build('inline');
$_e_[132] = $_b_->build('span');
$_e_[132]->set('eid', 'stara_cena_dph');
$_e_[132]->set('class', 'old4');
$_e_[131]->set('eid', 'ma_starou_cenu');
$_e_[131]->add($_e_[132]);
$_e_[133] = $_b_->build('span');
$_e_[134] = $_b_->build('he');
$_e_[134]->set('code', 'mdash');
$_e_[133]->set('eid', 'nema_starou_cenu');
$_e_[133]->set('class', 'old4');
$_e_[133]->add($_e_[134]);
$_e_[135] = $_b_->build('inline');
$_e_[136] = $_b_->build('span');
$_e_[136]->set('eid', 'nova_cena_dph');
$_e_[136]->set('class', 'new4');
$_e_[135]->set('eid', 'ma_novou_cenu');
$_e_[135]->add($_e_[136]);
$_e_[137] = $_b_->build('span');
$_e_[138] = $_b_->build('he');
$_e_[138]->set('code', 'mdash');
$_e_[137]->set('eid', 'nema_novou_cenu');
$_e_[137]->set('class', 'new4');
$_e_[137]->add($_e_[138]);
$_e_[130]->set('class', 'hodnota');
$_e_[130]->set('rowspan', '1');
$_e_[130]->set('colspan', '1');
$_e_[130]->add($_e_[131]);
$_e_[130]->add($_e_[133]);
$_e_[130]->add($_e_[135]);
$_e_[130]->add($_e_[137]);
$_e_[126]->set('active', '0');
$_e_[126]->add($_e_[127]);
$_e_[126]->add($_e_[130]);
$_e_[99]->set('cellspacing', '0');
$_e_[99]->set('cellpadding', '0');
$_e_[99]->add($_e_[100]);
$_e_[99]->add($_e_[101]);
$_e_[99]->add($_e_[113]);
$_e_[99]->add($_e_[126]);
$_e_[139] = $_b_->build('newline');
$_e_[98]->set('class', 'tab-detail-V');
$_e_[98]->add($_e_[99]);
$_e_[98]->add($_e_[139]);
$_e_[140] = $_b_->build('div');
$_e_[141] = $_b_->build('flow');
$_e_[142] = $_b_->build('h3');
$_e_[143] = $_b_->build('text_content');
$_e_[143]->set('text', 'Soubory ke stažení');
$_e_[142]->add($_e_[143]);
$_e_[144] = $_b_->build('flow');
$_e_[144]->set('eid', 'prilohy');
$_e_[141]->set('eid', 'ma_prilohy');
$_e_[141]->add($_e_[142]);
$_e_[141]->add($_e_[144]);
$_e_[140]->set('class', 'detail-prilohy');
$_e_[140]->add($_e_[141]);
$_e_[145] = $_b_->build('flow');
$_e_[145]->set('eid', 'nema_prilohy');
$_e_[97]->set('class', 't-d-para');
$_e_[97]->set('rowspan', '1');
$_e_[97]->set('colspan', '1');
$_e_[97]->add($_e_[98]);
$_e_[97]->add($_e_[140]);
$_e_[97]->add($_e_[145]);
$_e_[37]->add($_e_[38]);
$_e_[37]->add($_e_[97]);
$_e_[29]->set('class', 'tab-detail');
$_e_[29]->set('cellspacing', '0');
$_e_[29]->set('cellpadding', '0');
$_e_[29]->add($_e_[30]);
$_e_[29]->add($_e_[33]);
$_e_[29]->add($_e_[37]);
$_e_[146] = $_b_->build('div');
$_e_[147] = $_b_->build('text');
$_e_[147]->set('eid', 'popis');
$_e_[146]->set('eid', 'ma_popis');
$_e_[146]->set('class', 'detail-popis');
$_e_[146]->set('active', '0');
$_e_[146]->add($_e_[147]);
$_e_[148] = $_b_->build('flow');
$_e_[148]->set('eid', 'nema_popis');
$_e_[149] = $_b_->build('div');
$_e_[150] = $_b_->build('h3');
$_e_[151] = $_b_->build('text_content');
$_e_[151]->set('text', 'Ilustrativní fotografie');
$_e_[150]->add($_e_[151]);
$_e_[152] = $_b_->build('flow');
$_e_[152]->set('eid', 'ilustrativni_fotografie');
$_e_[153] = $_b_->build('br');
$_e_[153]->set('class', 'clear');
$_e_[149]->set('eid', 'ma_ilustrativni_fotografie');
$_e_[149]->set('class', 'ilustrativni-foto');
$_e_[149]->add($_e_[150]);
$_e_[149]->add($_e_[152]);
$_e_[149]->add($_e_[153]);
$_e_[154] = $_b_->build('flow');
$_e_[154]->set('eid', 'nema_ilustrativni_fotografie');
$_e_[155] = $_b_->build('div');
$_e_[156] = $_b_->build('h3');
$_e_[157] = $_b_->build('text_content');
$_e_[157]->set('text', 'Související produkty');
$_e_[156]->add($_e_[157]);
$_e_[158] = $_b_->build('flow');
$_e_[158]->set('eid', 'fotografie_kolekce');
$_e_[159] = $_b_->build('br');
$_e_[159]->set('class', 'clear');
$_e_[155]->set('eid', 'ma_fotografie_kolekce');
$_e_[155]->set('class', 'kolekce-foto');
$_e_[155]->add($_e_[156]);
$_e_[155]->add($_e_[158]);
$_e_[155]->add($_e_[159]);
$_e_[160] = $_b_->build('flow');
$_e_[160]->set('eid', 'nema_fotografie_kolekce');
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[3]);
$_e_[0]->add($_e_[29]);
$_e_[0]->add($_e_[146]);
$_e_[0]->add($_e_[148]);
$_e_[0]->add($_e_[149]);
$_e_[0]->add($_e_[154]);
$_e_[0]->add($_e_[155]);
$_e_[0]->add($_e_[160]);
?>