<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('div');
$_e_[2] = $_b_->build('div');
$_e_[3] = $_b_->build('div');
$_e_[4] = $_b_->build('div');
$_e_[5] = $_b_->build('div');
$_e_[6] = $_b_->build('navpoint');
$_e_[7] = $_b_->build('img');
$_e_[7]->set('src', '../image/logo-spodni.png');
$_e_[7]->set('alt', 'logo spitzen wein');
$_e_[6]->set('page', 'úvod');
$_e_[6]->set('title', 'zum start page');
$_e_[6]->add($_e_[7]);
$_e_[5]->set('class', 'spodni-adresy');
$_e_[5]->add($_e_[6]);
$_e_[4]->set('class', 'spodniL span4');
$_e_[4]->add($_e_[5]);
$_e_[8] = $_b_->build('div');
$_e_[9] = $_b_->build('div');
$_e_[10] = $_b_->build('div');
$_e_[11] = $_b_->build('h2');
$_e_[12] = $_b_->build('text_content');
$_e_[12]->set('text', 'Unseren Wein geniessen und dabei enorm sparen ... ');
$_e_[11]->add($_e_[12]);
$_e_[13] = $_b_->build('h2');
$_e_[14] = $_b_->build('text_content');
$_e_[14]->set('text', 'Das Leben ist zu kurz um schlechten Wein zu trinken.');
$_e_[13]->add($_e_[14]);
$_e_[10]->set('class', 'text-spodni');
$_e_[10]->add($_e_[11]);
$_e_[10]->add($_e_[13]);
$_e_[9]->set('class', 'spodni-kontakty');
$_e_[9]->add($_e_[10]);
$_e_[8]->set('class', 'spodniP span7');
$_e_[8]->add($_e_[9]);
$_e_[3]->set('class', 'spodni');
$_e_[3]->add($_e_[4]);
$_e_[3]->add($_e_[8]);
$_e_[2]->set('class', 'spodniV');
$_e_[2]->add($_e_[3]);
$_e_[1]->set('class', 'spodniBG');
$_e_[1]->add($_e_[2]);
$_e_[0]->add($_e_[1]);
?>