<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('flow');
$_e_[2] = $_b_->build('div');
$_e_[3] = $_b_->build('flow');
$_e_[3]->set('eid', 'obsah');
$_e_[2]->set('class', 'obsah');
$_e_[2]->add($_e_[3]);
$_e_[1]->set('eid', 'ma_obsah');
$_e_[1]->add($_e_[2]);
$_e_[4] = $_b_->build('flow');
$_e_[5] = $_b_->build('div');
$_e_[6] = $_b_->build('p');
$_e_[5]->set('class', 'obsah');
$_e_[5]->add($_e_[6]);
$_e_[4]->set('eid', 'nema_obsah');
$_e_[4]->add($_e_[5]);
$_e_[7] = $_b_->build('flow');
$_e_[8] = $_b_->build('div');
$_e_[9] = $_b_->build('h2');
$_e_[10] = $_b_->build('text_content');
$_e_[10]->set('text', 'Warnung!');
$_e_[9]->add($_e_[10]);
$_e_[11] = $_b_->build('br');
$_e_[12] = $_b_->build('p');
$_e_[13] = $_b_->build('text_content');
$_e_[13]->set('text', 'Sorry, aber der Inhalt dieser Website ist vorübergehend nicht erreichbar.');
$_e_[12]->add($_e_[13]);
$_e_[14] = $_b_->build('br');
$_e_[15] = $_b_->build('br');
$_e_[16] = $_b_->build('br');
$_e_[8]->set('class', 'obsah');
$_e_[8]->add($_e_[9]);
$_e_[8]->add($_e_[11]);
$_e_[8]->add($_e_[12]);
$_e_[8]->add($_e_[14]);
$_e_[8]->add($_e_[15]);
$_e_[8]->add($_e_[16]);
$_e_[7]->set('eid', 'neni_aktivni');
$_e_[7]->add($_e_[8]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[4]);
$_e_[0]->add($_e_[7]);
?>