<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('require');
$_e_[2] = $_b_->build('javascript');
$_e_[2]->set('src', 'http://map.search.ch/api/map.js');
$_e_[1]->add($_e_[2]);
$_e_[3] = $_b_->build('body');
$_e_[4] = $_b_->build('div');
$_e_[5] = $_b_->build('div');
$_e_[6] = $_b_->build('div');
$_e_[7] = $_b_->build('div');
$_e_[8] = $_b_->build('article');
$_e_[8]->set('template', 'article/logo');
$_e_[7]->set('class', 'horniL span6');
$_e_[7]->add($_e_[8]);
$_e_[9] = $_b_->build('div');
$_e_[9]->set('class', 'horniP span6');
$_e_[10] = $_b_->build('navmenu');
$_e_[10]->set('template', 'navmenu/hlavni-menu');
$_e_[10]->set('autodetect', 'on');
$_e_[6]->set('class', 'horni span12');
$_e_[6]->add($_e_[7]);
$_e_[6]->add($_e_[9]);
$_e_[6]->add($_e_[10]);
$_e_[5]->set('class', 'horniV');
$_e_[5]->add($_e_[6]);
$_e_[4]->set('class', 'horniBG');
$_e_[4]->add($_e_[5]);
$_e_[11] = $_b_->build('div');
$_e_[12] = $_b_->build('div');
$_e_[13] = $_b_->build('div');
$_e_[14] = $_b_->build('div');
$_e_[15] = $_b_->build('news');
$_e_[15]->set('mid', '7');
$_e_[15]->set('template', 'news/filialen');
$_e_[15]->set('images', 'lightbox');
$_e_[15]->set('detailpage', 'filialen detail');
$_e_[15]->set('ns', '');
$_e_[15]->set('nsd', '');
$_e_[15]->set('active', '1');
$_e_[14]->set('class', 'teloS span12');
$_e_[14]->add($_e_[15]);
$_e_[16] = $_b_->build('br');
$_e_[16]->set('class', 'clear');
$_e_[13]->set('class', 'telo');
$_e_[13]->add($_e_[14]);
$_e_[13]->add($_e_[16]);
$_e_[12]->set('class', 'teloV');
$_e_[12]->add($_e_[13]);
$_e_[11]->set('class', 'teloBG');
$_e_[11]->add($_e_[12]);
$_e_[17] = $_b_->build('article');
$_e_[17]->set('template', 'article/spodni');
$_e_[18] = $_b_->build('article');
$_e_[18]->set('template', 'article/copyright');
$_e_[3]->set('id', 'peak');
$_e_[3]->set('class', 'bv0');
$_e_[3]->add($_e_[4]);
$_e_[11]->set('comment', array('test'));
$_e_[3]->add($_e_[11]);
$_e_[3]->add($_e_[17]);
$_e_[3]->add($_e_[18]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[3]);
?>