<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('div');
$_e_[2] = $_b_->build('h2');
$_e_[3] = $_b_->build('text_content');
$_e_[3]->set('text', 'Neuheit');
$_e_[2]->add($_e_[3]);
$_e_[4] = $_b_->build('div');
$_e_[5] = $_b_->build('datetime');
$_e_[5]->set('template', '/datetime/teloL-aktuality');
$_e_[6] = $_b_->build('h3');
$_e_[7] = $_b_->build('span');
$_e_[8] = $_b_->build('text_content');
$_e_[8]->set('text', 'Nicht verfügbar');
$_e_[7]->add($_e_[8]);
$_e_[6]->add($_e_[7]);
$_e_[9] = $_b_->build('div');
$_e_[10] = $_b_->build('span');
$_e_[11] = $_b_->build('text_content');
$_e_[11]->set('text', 'Leider, aber dieser Artikel wurde entfernt.');
$_e_[10]->set('class', 'pozor');
$_e_[10]->add($_e_[11]);
$_e_[12] = $_b_->build('br');
$_e_[12]->set('class', 'clear');
$_e_[9]->set('class', 'news-obsah');
$_e_[9]->add($_e_[10]);
$_e_[9]->add($_e_[12]);
$_e_[13] = $_b_->build('div');
$_e_[14] = $_b_->build('span');
$_e_[15] = $_b_->build('text_content');
$_e_[15]->set('text', 'Autor: ');
$_e_[16] = $_b_->build('strong');
$_e_[17] = $_b_->build('text_content');
$_e_[17]->set('text', 'Content Management System Kiwi');
$_e_[16]->add($_e_[17]);
$_e_[14]->add($_e_[15]);
$_e_[14]->add($_e_[16]);
$_e_[13]->set('class', 'news-lista');
$_e_[13]->add($_e_[14]);
$_e_[4]->set('eid', 'neni_novinka');
$_e_[4]->set('class', 'news');
$_e_[4]->add($_e_[5]);
$_e_[4]->add($_e_[6]);
$_e_[4]->add($_e_[9]);
$_e_[4]->add($_e_[13]);
$_e_[18] = $_b_->build('div');
$_e_[19] = $_b_->build('div');
$_e_[20] = $_b_->build('datetime');
$_e_[20]->set('eid', 'datum');
$_e_[20]->set('template', '/datetime/teloL-aktuality');
$_e_[21] = $_b_->build('h3');
$_e_[22] = $_b_->build('span');
$_e_[23] = $_b_->build('text');
$_e_[23]->set('eid', 'nadpis');
$_e_[22]->add($_e_[23]);
$_e_[21]->add($_e_[22]);
$_e_[24] = $_b_->build('br');
$_e_[24]->set('class', 'clear');
$_e_[19]->add($_e_[20]);
$_e_[19]->add($_e_[21]);
$_e_[19]->add($_e_[24]);
$_e_[25] = $_b_->build('div');
$_e_[26] = $_b_->build('inline');
$_e_[26]->set('eid', 'obsah');
$_e_[27] = $_b_->build('br');
$_e_[27]->set('class', 'clear');
$_e_[25]->set('class', 'news-obsah');
$_e_[25]->add($_e_[26]);
$_e_[25]->add($_e_[27]);
$_e_[28] = $_b_->build('div');
$_e_[29] = $_b_->build('span');
$_e_[30] = $_b_->build('text_content');
$_e_[30]->set('text', 'Autor: ');
$_e_[31] = $_b_->build('strong');
$_e_[32] = $_b_->build('text');
$_e_[32]->set('eid', 'autor');
$_e_[31]->add($_e_[32]);
$_e_[29]->set('class', 'autor');
$_e_[29]->add($_e_[30]);
$_e_[29]->add($_e_[31]);
$_e_[33] = $_b_->build('span');
$_e_[34] = $_b_->build('navpoint');
$_e_[35] = $_b_->build('text_content');
$_e_[35]->set('text', 'zurück zur alles Aktuell list');
$_e_[34]->set('page', 'aktuality');
$_e_[34]->add($_e_[35]);
$_e_[33]->set('class', 'odkaz');
$_e_[33]->add($_e_[34]);
$_e_[28]->set('class', 'news-lista');
$_e_[28]->add($_e_[29]);
$_e_[28]->add($_e_[33]);
$_e_[18]->set('eid', 'je_novinka');
$_e_[18]->set('class', 'news');
$_e_[18]->add($_e_[19]);
$_e_[18]->add($_e_[25]);
$_e_[18]->add($_e_[28]);
$_e_[1]->set('class', 'teloP-news');
$_e_[1]->add($_e_[2]);
$_e_[1]->add($_e_[4]);
$_e_[1]->add($_e_[18]);
$_e_[0]->add($_e_[1]);
?>