<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('group');
$_e_[2] = $_b_->build('flow');
$_e_[3] = $_b_->build('datetime');
$_e_[3]->set('active', '0');
$_e_[3]->set('eid', 'datum');
$_e_[3]->set('template', '/datetime/teloL-aktuality');
$_e_[4] = $_b_->build('flow');
$_e_[5] = $_b_->build('a');
$_e_[6] = $_b_->build('text');
$_e_[6]->set('eid', 'nadpis');
$_e_[5]->set('eid', 'detail');
$_e_[5]->set('title', 'weiter lesen');
$_e_[5]->set('shape', 'rect');
$_e_[5]->add($_e_[6]);
$_e_[4]->set('eid', 'ma_detail');
$_e_[4]->add($_e_[5]);
$_e_[7] = $_b_->build('flow');
$_e_[8] = $_b_->build('span');
$_e_[9] = $_b_->build('text');
$_e_[9]->set('eid', 'nadpis');
$_e_[8]->add($_e_[9]);
$_e_[7]->set('eid', 'nema_detail');
$_e_[7]->add($_e_[8]);
$_e_[10] = $_b_->build('flow');
$_e_[10]->set('eid', 'obsah');
$_e_[10]->set('active', '0');
$_e_[2]->set('eid', 'novinka_vzor');
$_e_[2]->add($_e_[3]);
$_e_[2]->add($_e_[4]);
$_e_[2]->add($_e_[7]);
$_e_[2]->add($_e_[10]);
$_e_[1]->set('active', '0');
$_e_[1]->add($_e_[2]);
$_e_[11] = $_b_->build('div');
$_e_[12] = $_b_->build('h2');
$_e_[13] = $_b_->build('text_content');
$_e_[13]->set('text', 'Unsere Filialen');
$_e_[12]->add($_e_[13]);
$_e_[14] = $_b_->build('flow');
$_e_[14]->set('eid', 'zadne_novinky');
$_e_[15] = $_b_->build('flow');
$_e_[15]->set('eid', 'prazdna_stranka');
$_e_[16] = $_b_->build('flow');
$_e_[16]->set('eid', 'novinky');
$_e_[17] = $_b_->build('pagination');
$_e_[17]->set('eid', 'dolni_paginace');
$_e_[17]->set('vid', 'paginace');
$_e_[17]->set('case', 'bottom');
$_e_[17]->set('radius', '2');
$_e_[17]->set('template', 'pagination/teloL-aktuality');
$_e_[11]->set('class', 'filialen-menu');
$_e_[11]->add($_e_[12]);
$_e_[11]->add($_e_[14]);
$_e_[11]->add($_e_[15]);
$_e_[11]->add($_e_[16]);
$_e_[11]->add($_e_[17]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[11]);
?>