<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('div');
$_e_[2] = $_b_->build('h3');
$_e_[3] = $_b_->build('text_content');
$_e_[3]->set('text', 'Není k dispozici');
$_e_[2]->add($_e_[3]);
$_e_[4] = $_b_->build('text_content');
$_e_[4]->set('text', '
Je nám líto, ale tento článek byl odstraněn.
');
$_e_[5] = $_b_->build('div');
$_e_[6] = $_b_->build('datetime');
$_e_[7] = $_b_->build('span');
$_e_[8] = $_b_->build('text_content');
$_e_[8]->set('text', 'Autor: ');
$_e_[9] = $_b_->build('strong');
$_e_[10] = $_b_->build('text_content');
$_e_[10]->set('text', 'Systém');
$_e_[9]->add($_e_[10]);
$_e_[7]->add($_e_[8]);
$_e_[7]->add($_e_[9]);
$_e_[5]->set('class', 'news-lista');
$_e_[5]->add($_e_[6]);
$_e_[5]->add($_e_[7]);
$_e_[1]->set('eid', 'neni_novinka');
$_e_[1]->set('class', 'news');
$_e_[1]->add($_e_[2]);
$_e_[1]->add($_e_[4]);
$_e_[1]->add($_e_[5]);
$_e_[11] = $_b_->build('div');
$_e_[12] = $_b_->build('div');
$_e_[13] = $_b_->build('div');
$_e_[14] = $_b_->build('datetime');
$_e_[14]->set('active', '0');
$_e_[14]->set('eid', 'datum');
$_e_[14]->set('template', '/datetime/teloL-aktuality');
$_e_[15] = $_b_->build('h3');
$_e_[16] = $_b_->build('span');
$_e_[17] = $_b_->build('text');
$_e_[17]->set('eid', 'nadpis');
$_e_[16]->add($_e_[17]);
$_e_[15]->set('class', 'prodejna-nadpis');
$_e_[15]->add($_e_[16]);
$_e_[18] = $_b_->build('br');
$_e_[18]->set('class', 'clear');
$_e_[13]->add($_e_[14]);
$_e_[13]->add($_e_[15]);
$_e_[13]->add($_e_[18]);
$_e_[19] = $_b_->build('div');
$_e_[20] = $_b_->build('inline');
$_e_[20]->set('eid', 'obsah');
$_e_[21] = $_b_->build('br');
$_e_[21]->set('class', 'clear');
$_e_[19]->set('class', 'prodejna-obsah');
$_e_[19]->add($_e_[20]);
$_e_[19]->add($_e_[21]);
$_e_[12]->set('eid', 'je_novinka');
$_e_[12]->set('class', 'prodejna-detail');
$_e_[12]->add($_e_[13]);
$_e_[12]->add($_e_[19]);
$_e_[11]->set('class', 'telo-prodejny');
$_e_[11]->add($_e_[12]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[11]);
?>