<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('group');
$_e_[2] = $_b_->build('article');
$_e_[3] = $_b_->build('img');
$_e_[3]->set('src', '/img/ok.png');
$_e_[3]->set('alt', 'ok');
$_e_[2]->set('vid', 'ok');
$_e_[2]->add($_e_[3]);
$_e_[4] = $_b_->build('article');
$_e_[5] = $_b_->build('img');
$_e_[5]->set('src', '/img/error.png');
$_e_[5]->set('alt', 'error');
$_e_[4]->set('vid', 'error');
$_e_[4]->add($_e_[5]);
$_e_[1]->set('active', '0');
$_e_[1]->add($_e_[2]);
$_e_[1]->add($_e_[4]);
$_e_[6] = $_b_->build('require');
$_e_[7] = $_b_->build('javascript');
$_e_[7]->set('src', '/js/mailer_form.js');
$_e_[6]->set('active', '0');
$_e_[6]->add($_e_[7]);
$_e_[8] = $_b_->build('div');
$_e_[9] = $_b_->build('h2');
$_e_[10] = $_b_->build('text_content');
$_e_[10]->set('text', 'KONTAKTIEREN SIE UNS');
$_e_[9]->add($_e_[10]);
$_e_[11] = $_b_->build('p');
$_e_[12] = $_b_->build('text_content');
$_e_[12]->set('text', 'Wir sind bestrebt unseren Kunden den besten Service und viel Freude am Einkaufen zu bieten. Deshalb schätzen wir Ihre Kommentare und Anregungen. Gerne beantworten wir Ihre Fragen.');
$_e_[11]->set('class', 'text');
$_e_[11]->add($_e_[12]);
$_e_[13] = $_b_->build('flow');
$_e_[14] = $_b_->build('flow');
$_e_[15] = $_b_->build('text_content');
$_e_[15]->set('text', 'Das Formular enthält ungültige Eingabewerte. (');
$_e_[16] = $_b_->build('inline');
$_e_[16]->set('eid', 'validation_failures');
$_e_[17] = $_b_->build('text_content');
$_e_[17]->set('text', ')');
$_e_[14]->set('active', '0');
$_e_[14]->add($_e_[15]);
$_e_[14]->add($_e_[16]);
$_e_[14]->add($_e_[17]);
$_e_[18] = $_b_->build('javascript');
$_e_[19] = $_b_->build('text_content');
$_e_[19]->set('text', 'location.hash = \'vzkaz\';');
$_e_[18]->add($_e_[19]);
$_e_[13]->set('eid', 'validation_failed');
$_e_[13]->add($_e_[14]);
$_e_[13]->add($_e_[18]);
$_e_[20] = $_b_->build('div');
$_e_[21] = $_b_->build('flow');
$_e_[22] = $_b_->build('div');
$_e_[23] = $_b_->build('text_content');
$_e_[23]->set('text', 'Das Formular enthält (');
$_e_[24] = $_b_->build('inline');
$_e_[24]->set('eid', 'validation_failures');
$_e_[25] = $_b_->build('text_content');
$_e_[25]->set('text', ') Fehler. Bitte füllen Sie die Felder mit einem roten ausrufezeichen gekennzeichnet (');
$_e_[26] = $_b_->build('strong');
$_e_[27] = $_b_->build('text_content');
$_e_[27]->set('text', '!');
$_e_[26]->set('class', 'error');
$_e_[26]->add($_e_[27]);
$_e_[28] = $_b_->build('text_content');
$_e_[28]->set('text', '). Danke.');
$_e_[22]->set('class', 'formular-chyby');
$_e_[22]->add($_e_[23]);
$_e_[22]->add($_e_[24]);
$_e_[22]->add($_e_[25]);
$_e_[22]->add($_e_[26]);
$_e_[22]->add($_e_[28]);
$_e_[29] = $_b_->build('javascript');
$_e_[30] = $_b_->build('text_content');
$_e_[30]->set('text', 'location.hash = \'vzkaz\';');
$_e_[29]->add($_e_[30]);
$_e_[21]->set('eid', 'validation_failed');
$_e_[21]->add($_e_[22]);
$_e_[21]->add($_e_[29]);
$_e_[31] = $_b_->build('form');
$_e_[32] = $_b_->build('div');
$_e_[33] = $_b_->build('input');
$_e_[33]->set('type', 'hidden');
$_e_[33]->set('eid', 'identification');
$_e_[33]->set('name', 'mailer');
$_e_[33]->set('value', '1');
$_e_[34] = $_b_->build('autoinput');
$_e_[34]->set('formid', 'mailer');
$_e_[34]->set('eid', 'hidden');
$_e_[34]->set('id', 'jsv');
$_e_[34]->set('name', 'jsv');
$_e_[34]->set('type', 'hidden');
$_e_[35] = $_b_->build('div');
$_e_[36] = $_b_->build('span');
$_e_[37] = $_b_->build('text_content');
$_e_[37]->set('text', 'Name: ');
$_e_[38] = $_b_->build('inline');
$_e_[39] = $_b_->build('strong');
$_e_[40] = $_b_->build('text_content');
$_e_[40]->set('text', '!');
$_e_[39]->set('class', 'error');
$_e_[39]->add($_e_[40]);
$_e_[38]->set('eid', 'validation');
$_e_[38]->set('specification', 'jmeno/missing');
$_e_[38]->add($_e_[39]);
$_e_[41] = $_b_->build('inline');
$_e_[41]->set('eid', 'validation');
$_e_[41]->set('specification', 'jmeno/ok');
$_e_[36]->add($_e_[37]);
$_e_[36]->add($_e_[38]);
$_e_[36]->add($_e_[41]);
$_e_[42] = $_b_->build('autoinput');
$_e_[42]->set('formid', 'mailer');
$_e_[42]->set('eid', 'trap');
$_e_[42]->set('name', 'fjmeno');
$_e_[42]->set('type', 'text');
$_e_[42]->set('value', '');
$_e_[42]->set('class', 'iinp2');
$_e_[43] = $_b_->build('autoinput');
$_e_[43]->set('formid', 'mailer');
$_e_[43]->set('eid', 'jmeno');
$_e_[43]->set('name', 'jmeno');
$_e_[43]->set('type', 'text');
$_e_[43]->set('value', '');
$_e_[43]->set('class', 'inp2');
$_e_[35]->set('class', 'kontakt-jmeno');
$_e_[35]->add($_e_[36]);
$_e_[35]->add($_e_[42]);
$_e_[35]->add($_e_[43]);
$_e_[44] = $_b_->build('div');
$_e_[45] = $_b_->build('span');
$_e_[46] = $_b_->build('text_content');
$_e_[46]->set('text', 'Telefon: ');
$_e_[47] = $_b_->build('inline');
$_e_[48] = $_b_->build('strong');
$_e_[49] = $_b_->build('text_content');
$_e_[49]->set('text', '!');
$_e_[48]->set('class', 'error');
$_e_[48]->add($_e_[49]);
$_e_[47]->set('eid', 'validation');
$_e_[47]->set('specification', 'telefon_syntax/invalid');
$_e_[47]->add($_e_[48]);
$_e_[50] = $_b_->build('inline');
$_e_[50]->set('eid', 'validation');
$_e_[50]->set('specification', 'telefon_syntax/ok');
$_e_[45]->add($_e_[46]);
$_e_[45]->add($_e_[47]);
$_e_[45]->add($_e_[50]);
$_e_[51] = $_b_->build('autoinput');
$_e_[51]->set('formid', 'mailer');
$_e_[51]->set('eid', 'trap');
$_e_[51]->set('name', 'ftelefon');
$_e_[51]->set('type', 'text');
$_e_[51]->set('value', '');
$_e_[51]->set('class', 'iinp2');
$_e_[52] = $_b_->build('autoinput');
$_e_[52]->set('formid', 'mailer');
$_e_[52]->set('eid', 'telefon');
$_e_[52]->set('name', 'telefon');
$_e_[52]->set('type', 'text');
$_e_[52]->set('value', '');
$_e_[52]->set('class', 'inp2');
$_e_[44]->set('class', 'kontakt-telefon');
$_e_[44]->add($_e_[45]);
$_e_[44]->add($_e_[51]);
$_e_[44]->add($_e_[52]);
$_e_[53] = $_b_->build('div');
$_e_[54] = $_b_->build('span');
$_e_[55] = $_b_->build('text_content');
$_e_[55]->set('text', 'E-mail: ');
$_e_[56] = $_b_->build('inline');
$_e_[57] = $_b_->build('strong');
$_e_[58] = $_b_->build('text_content');
$_e_[58]->set('text', '!');
$_e_[57]->set('class', 'error');
$_e_[57]->add($_e_[58]);
$_e_[56]->set('eid', 'validation');
$_e_[56]->set('specification', 'email/missing');
$_e_[56]->add($_e_[57]);
$_e_[59] = $_b_->build('inline');
$_e_[60] = $_b_->build('strong');
$_e_[61] = $_b_->build('text_content');
$_e_[61]->set('text', '!');
$_e_[60]->set('class', 'error');
$_e_[60]->add($_e_[61]);
$_e_[59]->set('eid', 'validation');
$_e_[59]->set('specification', 'email/invalid');
$_e_[59]->add($_e_[60]);
$_e_[62] = $_b_->build('inline');
$_e_[62]->set('eid', 'validation');
$_e_[62]->set('specification', 'email/ok');
$_e_[54]->add($_e_[55]);
$_e_[54]->add($_e_[56]);
$_e_[54]->add($_e_[59]);
$_e_[54]->add($_e_[62]);
$_e_[63] = $_b_->build('autoinput');
$_e_[63]->set('formid', 'mailer');
$_e_[63]->set('eid', 'trap');
$_e_[63]->set('name', 'femail');
$_e_[63]->set('type', 'text');
$_e_[63]->set('value', '@');
$_e_[63]->set('class', 'iinp2');
$_e_[64] = $_b_->build('autoinput');
$_e_[64]->set('formid', 'mailer');
$_e_[64]->set('eid', 'email');
$_e_[64]->set('name', 'email');
$_e_[64]->set('type', 'text');
$_e_[64]->set('value', '@');
$_e_[64]->set('class', 'inp2');
$_e_[53]->set('class', 'kontakt-email');
$_e_[53]->add($_e_[54]);
$_e_[53]->add($_e_[63]);
$_e_[53]->add($_e_[64]);
$_e_[65] = $_b_->build('br');
$_e_[65]->set('class', 'clear');
$_e_[66] = $_b_->build('div');
$_e_[67] = $_b_->build('span');
$_e_[68] = $_b_->build('text_content');
$_e_[68]->set('text', 'Ihre Nachricht: ');
$_e_[69] = $_b_->build('inline');
$_e_[70] = $_b_->build('strong');
$_e_[71] = $_b_->build('text_content');
$_e_[71]->set('text', '!');
$_e_[70]->set('class', 'error');
$_e_[70]->add($_e_[71]);
$_e_[69]->set('eid', 'validation');
$_e_[69]->set('specification', 'vzkaz/missing');
$_e_[69]->add($_e_[70]);
$_e_[72] = $_b_->build('inline');
$_e_[72]->set('eid', 'validation');
$_e_[72]->set('specification', 'vzkaz/ok');
$_e_[67]->add($_e_[68]);
$_e_[67]->add($_e_[69]);
$_e_[67]->add($_e_[72]);
$_e_[73] = $_b_->build('autotextarea');
$_e_[73]->set('formid', 'mailer');
$_e_[73]->set('eid', 'trap');
$_e_[73]->set('name', 'fvzkaz');
$_e_[73]->set('class', 'itextarea');
$_e_[73]->set('rows', '0');
$_e_[73]->set('cols', '0');
$_e_[74] = $_b_->build('autotextarea');
$_e_[74]->set('formid', 'mailer');
$_e_[74]->set('eid', 'vzkaz');
$_e_[74]->set('name', 'vzkaz');
$_e_[74]->set('class', 'textarea');
$_e_[74]->set('rows', '0');
$_e_[74]->set('cols', '0');
$_e_[66]->set('class', 'kontakt-vzkaz');
$_e_[66]->add($_e_[67]);
$_e_[66]->add($_e_[73]);
$_e_[66]->add($_e_[74]);
$_e_[75] = $_b_->build('br');
$_e_[75]->set('class', 'clear');
$_e_[76] = $_b_->build('autoinput');
$_e_[76]->set('formid', 'mailer');
$_e_[76]->set('eid', 'odeslat');
$_e_[76]->set('name', 'submit');
$_e_[76]->set('type', 'submit');
$_e_[76]->set('value', 'Senden');
$_e_[76]->set('class', 'but5');
$_e_[76]->set('onclick', 'return Mailer_Form.onSubmit(\'jsv\')');
$_e_[77] = $_b_->build('autoinput');
$_e_[77]->set('formid', 'mailer');
$_e_[77]->set('eid', 'trap');
$_e_[77]->set('name', 'fsubmit');
$_e_[77]->set('type', 'submit');
$_e_[77]->set('value', 'Odeslat Fake');
$_e_[77]->set('class', 'ibut5');
$_e_[77]->set('onclick', 'return Mailer_Form.onSubmit(\'jsv\')');
$_e_[78] = $_b_->build('input');
$_e_[78]->set('type', 'reset');
$_e_[78]->set('value', 'ZRUŠIT');
$_e_[78]->set('class', 'but3');
$_e_[79] = $_b_->build('div');
$_e_[80] = $_b_->build('article');
$_e_[80]->set('vid', 'ok');
$_e_[81] = $_b_->build('text_content');
$_e_[81]->set('text', 'Ok');
$_e_[79]->set('eid', 'validation_passed');
$_e_[79]->add($_e_[80]);
$_e_[79]->add($_e_[81]);
$_e_[82] = $_b_->build('br');
$_e_[82]->set('class', 'clear');
$_e_[32]->add($_e_[33]);
$_e_[32]->add($_e_[34]);
$_e_[32]->add($_e_[35]);
$_e_[32]->add($_e_[44]);
$_e_[32]->add($_e_[53]);
$_e_[32]->add($_e_[65]);
$_e_[32]->add($_e_[66]);
$_e_[32]->add($_e_[75]);
$_e_[32]->add($_e_[76]);
$_e_[32]->add($_e_[77]);
$_e_[32]->add($_e_[78]);
$_e_[32]->add($_e_[79]);
$_e_[32]->add($_e_[82]);
$_e_[31]->set('render', 'js');
$_e_[31]->set('method', 'post');
$_e_[31]->set('action', '');
$_e_[31]->set('enctype', 'application/x-www-form-urlencoded');
$_e_[31]->add($_e_[32]);
$_e_[83] = $_b_->build('br');
$_e_[83]->set('class', 'clear');
$_e_[20]->set('class', 'formular');
$_e_[20]->set('id', 'vzkaz');
$_e_[20]->add($_e_[21]);
$_e_[20]->add($_e_[31]);
$_e_[20]->add($_e_[83]);
$_e_[8]->set('class', 'kontakt-formular');
$_e_[8]->add($_e_[9]);
$_e_[8]->add($_e_[11]);
$_e_[8]->add($_e_[13]);
$_e_[8]->add($_e_[20]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[6]);
$_e_[0]->add($_e_[8]);
?>