<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('head');
$_e_[2] = $_b_->build('hgroup');
$_e_[3] = $_b_->build('meta');
$_e_[3]->set('http-equiv', 'Content-Type');
$_e_[3]->set('content', 'text/html; charset=utf-8');
$_e_[4] = $_b_->build('meta');
$_e_[4]->set('name', 'description');
$_e_[4]->set('content', '...');
$_e_[4]->set('lang', 'cs');
$_e_[5] = $_b_->build('meta');
$_e_[5]->set('name', 'keywords');
$_e_[5]->set('content', '...');
$_e_[5]->set('lang', 'cs');
$_e_[6] = $_b_->build('meta');
$_e_[6]->set('name', 'author');
$_e_[6]->set('content', 'www.artprodesign.com');
$_e_[7] = $_b_->build('meta');
$_e_[7]->set('name', 'copyright');
$_e_[7]->set('content', 'sdruzeni artprodesign.com');
$_e_[2]->set('eid', 'metas');
$_e_[2]->add($_e_[3]);
$_e_[2]->add($_e_[4]);
$_e_[2]->add($_e_[5]);
$_e_[2]->add($_e_[6]);
$_e_[2]->add($_e_[7]);
$_e_[8] = $_b_->build('title');
$_e_[9] = $_b_->build('text_content');
$_e_[9]->set('text', 'Nachricht aus website spitzen-wein.ch');
$_e_[8]->add($_e_[9]);
$_e_[1]->add($_e_[2]);
$_e_[1]->add($_e_[8]);
$_e_[10] = $_b_->build('body');
$_e_[11] = $_b_->build('div');
$_e_[12] = $_b_->build('strong');
$_e_[13] = $_b_->build('text_content');
$_e_[13]->set('text', 'Thema: ');
$_e_[12]->add($_e_[13]);
$_e_[14] = $_b_->build('text_content');
$_e_[14]->set('text', ' ');
$_e_[15] = $_b_->build('span');
$_e_[15]->set('eid', 'predmet');
$_e_[16] = $_b_->build('br');
$_e_[17] = $_b_->build('flow');
$_e_[18] = $_b_->build('strong');
$_e_[19] = $_b_->build('text_content');
$_e_[19]->set('text', 'Name: ');
$_e_[18]->add($_e_[19]);
$_e_[20] = $_b_->build('span');
$_e_[20]->set('eid', 'jmeno');
$_e_[21] = $_b_->build('br');
$_e_[17]->set('eid', 'je_jmeno');
$_e_[17]->add($_e_[18]);
$_e_[17]->add($_e_[20]);
$_e_[17]->add($_e_[21]);
$_e_[22] = $_b_->build('flow');
$_e_[23] = $_b_->build('text_content');
$_e_[23]->set('text', 'Name wurde nicht erwähnt.');
$_e_[24] = $_b_->build('br');
$_e_[22]->set('eid', 'neni_jmeno');
$_e_[22]->add($_e_[23]);
$_e_[22]->add($_e_[24]);
$_e_[25] = $_b_->build('flow');
$_e_[26] = $_b_->build('strong');
$_e_[27] = $_b_->build('text_content');
$_e_[27]->set('text', 'E-mail: ');
$_e_[26]->add($_e_[27]);
$_e_[28] = $_b_->build('span');
$_e_[28]->set('eid', 'email');
$_e_[29] = $_b_->build('br');
$_e_[25]->set('eid', 'je_email');
$_e_[25]->add($_e_[26]);
$_e_[25]->add($_e_[28]);
$_e_[25]->add($_e_[29]);
$_e_[30] = $_b_->build('flow');
$_e_[31] = $_b_->build('text_content');
$_e_[31]->set('text', 'E-Mail-Adresse wird nicht aufgeführt.');
$_e_[32] = $_b_->build('br');
$_e_[30]->set('eid', 'neni_email');
$_e_[30]->add($_e_[31]);
$_e_[30]->add($_e_[32]);
$_e_[33] = $_b_->build('flow');
$_e_[34] = $_b_->build('strong');
$_e_[35] = $_b_->build('text_content');
$_e_[35]->set('text', 'Telefon: ');
$_e_[34]->add($_e_[35]);
$_e_[36] = $_b_->build('span');
$_e_[36]->set('eid', 'telefon');
$_e_[37] = $_b_->build('br');
$_e_[33]->set('eid', 'je_telefon');
$_e_[33]->add($_e_[34]);
$_e_[33]->add($_e_[36]);
$_e_[33]->add($_e_[37]);
$_e_[38] = $_b_->build('flow');
$_e_[39] = $_b_->build('text_content');
$_e_[39]->set('text', 'Telefon nicht aufgeführt.');
$_e_[40] = $_b_->build('br');
$_e_[38]->set('eid', 'neni_telefon');
$_e_[38]->add($_e_[39]);
$_e_[38]->add($_e_[40]);
$_e_[41] = $_b_->build('flow');
$_e_[42] = $_b_->build('strong');
$_e_[43] = $_b_->build('text_content');
$_e_[43]->set('text', 'Nachricht: ');
$_e_[42]->add($_e_[43]);
$_e_[44] = $_b_->build('br');
$_e_[45] = $_b_->build('flow');
$_e_[45]->set('eid', 'vzkaz');
$_e_[41]->set('eid', 'je_vzkaz');
$_e_[41]->add($_e_[42]);
$_e_[41]->add($_e_[44]);
$_e_[41]->add($_e_[45]);
$_e_[46] = $_b_->build('flow');
$_e_[47] = $_b_->build('text_content');
$_e_[47]->set('text', 'Nachricht wurde nicht angegeben.');
$_e_[46]->set('eid', 'neni_vzkaz');
$_e_[46]->add($_e_[47]);
$_e_[11]->add($_e_[12]);
$_e_[11]->add($_e_[14]);
$_e_[11]->add($_e_[15]);
$_e_[11]->add($_e_[16]);
$_e_[11]->add($_e_[17]);
$_e_[11]->add($_e_[22]);
$_e_[11]->add($_e_[25]);
$_e_[11]->add($_e_[30]);
$_e_[11]->add($_e_[33]);
$_e_[11]->add($_e_[38]);
$_e_[11]->add($_e_[41]);
$_e_[11]->add($_e_[46]);
$_e_[10]->add($_e_[11]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[10]);
?>