<?php
$_e_[0] = $_b_->build('group');
$_e_[1] = $_b_->build('require');
$_e_[2] = $_b_->build('link');
$_e_[2]->set('rel', 'stylesheet');
$_e_[2]->set('type', 'text/css');
$_e_[2]->set('href', '/styles/list-menu.css');
$_e_[1]->add($_e_[2]);
$_e_[3] = $_b_->build('group');
$_e_[4] = $_b_->build('li');
$_e_[5] = $_b_->build('a');
$_e_[6] = $_b_->build('inline');
$_e_[7] = $_b_->build('img');
$_e_[7]->set('eid', 'obrazek_banneru');
$_e_[6]->set('eid', 'ma_obrazek');
$_e_[6]->add($_e_[7]);
$_e_[8] = $_b_->build('inline');
$_e_[9] = $_b_->build('img');
$_e_[9]->set('src', '/img/banner_na.jpg');
$_e_[9]->set('alt', 'není k dispozici');
$_e_[8]->set('eid', 'nema_obrazek');
$_e_[8]->add($_e_[9]);
$_e_[5]->set('href', '#');
$_e_[5]->set('eid', 'odkaz_banneru');
$_e_[5]->set('shape', 'rect');
$_e_[5]->add($_e_[6]);
$_e_[5]->add($_e_[8]);
$_e_[10] = $_b_->build('div');
$_e_[11] = $_b_->build('h3');
$_e_[12] = $_b_->build('text');
$_e_[12]->set('eid', 'nadpis_banneru');
$_e_[11]->add($_e_[12]);
$_e_[13] = $_b_->build('inline');
$_e_[13]->set('eid', 'popis_banneru');
$_e_[10]->set('class', 'uvod-popis');
$_e_[10]->add($_e_[11]);
$_e_[10]->add($_e_[13]);
$_e_[4]->set('eid', 'banner_vzor');
$_e_[4]->add($_e_[5]);
$_e_[4]->add($_e_[10]);
$_e_[14] = $_b_->build('li');
$_e_[15] = $_b_->build('a');
$_e_[16] = $_b_->build('span');
$_e_[17] = $_b_->build('text');
$_e_[17]->set('eid', 'vyber_index');
$_e_[16]->set('class', 'lista-pagination');
$_e_[16]->add($_e_[17]);
$_e_[15]->set('href', '#');
$_e_[15]->set('shape', 'rect');
$_e_[15]->add($_e_[16]);
$_e_[14]->set('eid', 'vyber_vzor');
$_e_[14]->add($_e_[15]);
$_e_[3]->set('active', '0');
$_e_[3]->add($_e_[4]);
$_e_[3]->add($_e_[14]);
$_e_[18] = $_b_->build('flow');
$_e_[18]->set('eid', 'nejsou_bannery');
$_e_[19] = $_b_->build('flow');
$_e_[20] = $_b_->build('div');
$_e_[21] = $_b_->build('ul');
$_e_[21]->set('eid', 'bannery');
$_e_[21]->set('class', 'output');
$_e_[22] = $_b_->build('ul');
$_e_[22]->set('eid', 'bannery_vyber');
$_e_[22]->set('class', 'uvod-str');
$_e_[20]->set('class', 'uvod-list');
$_e_[20]->add($_e_[21]);
$_e_[20]->add($_e_[22]);
$_e_[19]->set('eid', 'jsou_bannery');
$_e_[19]->add($_e_[20]);
$_e_[0]->add($_e_[1]);
$_e_[0]->add($_e_[3]);
$_e_[0]->add($_e_[18]);
$_e_[0]->add($_e_[19]);
?>