<?php
$config = array
(
	'csv' => array
	(
		'separator' => ';'
	),
	'ppv_separators' => array
	(
		'default' => ',',
		'Erreichbarkeit' => '@',
		'Farbe' => '@',
		'Lieferzeit' => '@',
		'Variante' => '@',
		'Härtegrad' => '@',
		'Material' => '@',
		'Grösse' => '@',
		'Durchmesser' => '@',
		'Gesamthöhe' => '@',
		'Breite' => '@',
		'Länge' => '@',
		'Tiefe' => '@',
		'Länge' => '@',
		'Tiefe' => '@',
		'Kern' => '@',
		'Auflagen' => '@',
		'Bezug' => '@',
		'Garantie' => '@',
		'Pflege' => '@',
		'Hersteller' => '@',
		'Füllgewicht' => '@',
		'Gewicht' => '@',
		'Kernhöhe' => '@',
		'Matratzenhöhe' => '@',
		'Breite/Länge' => '@',
		'Matratzenhöhe' => '@',
		'Rahmenhöhe' => '@',
		'Höhe' => '@',
		'Hülle' => '@',
		'Beschlags-Set' => '@',
		'Florhöhe' => '@',
		'Serie' => '@'
	),
	'pl_separator' => '@',
	'columns' => array
	(
		'ID' => self::ID,
		'Code' => self::CODE,
		'Bezeichnung' => self::TITLE,
		'Erreichbarkeit' => self::PROPERTY,
		'Farbe' => self::PROPERTY,
		'Lieferzeit' => self::PROPERTY,
		'Variante' => self::PROPERTY,
		'Härtegrad' => self::PROPERTY,
		'Material' => self::PROPERTY,
		'Grösse' => self::PROPERTY,
		'Durchmesser' => self::PROPERTY,
		'Gesamthöhe' => self::PROPERTY,
		'Breite' => self::PROPERTY,
		'Länge' => self::PROPERTY,
		'Tiefe' => self::PROPERTY,
		'Länge' => self::PROPERTY,
		'Tiefe' => self::PROPERTY,
		'Kern' => self::PROPERTY,
		'Auflagen' => self::PROPERTY,
		'Bezug' => self::PROPERTY,
		'Garantie' => self::PROPERTY,
		'Pflege' => self::PROPERTY,
		'Hersteller' => self::PROPERTY,
		'Füllgewicht' => self::PROPERTY,
		'Gewicht' => self::PROPERTY,
		'Kernhöhe' => self::PROPERTY,
		'Matratzenhöhe' => self::PROPERTY,
		'Breite/Länge' => self::PROPERTY,
		'Matratzenhöhe' => self::PROPERTY,
		'Rahmenhöhe' => self::PROPERTY,
		'Höhe' => self::PROPERTY,
		'Hülle' => self::PROPERTY,
		'Beschlags-Set' => self::PROPERTY,
		'Florhöhe' => self::PROPERTY,
		'URL' => self::URL,
		'HTML Title' => self::PAGETITLE,
		'Kurzbeschreibung' => self::SHORTDESC,
		'Beschreibung' => self::LONGDESC,
		'Unsere Preis' => self::NEWCOST,
		'Original Preis' => self::ORIGINALCOST,
		'Serie' => self::PRODUCTLINES,
	)
);
?>